### post create

POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "post title",
    "content": "content",
    "authorEmail": "elky84@gmail.com"
}

### filtered-posts

GET http://localhost:3000/filtered-posts/cont


### feed

GET http://localhost:3000/feed

### post by id

GET http://localhost:3000/post/2

### publish post

PUT http://localhost:3000/publish/1

### post delete

DELETE http://localhost:3000/post/1
